### ISSUE TITLE
Rsync Limitation - Deployments

### ISSUE THREAD

**Issue by CNSam** [lorisleiva/laravel-deployer#105]
Hi folks,

So i'm following this link regarding gitlab deployments: https://lorisleiva.com/laravel-deployment-using-gitlab-pipelines/ and all is working well on a separate installation however Im now trying to implement the same on a more convoluted setup.

Basically we have a 'data-storage' server (freenas) which is mounted onto our php-node on an internal virtual cluster. (don't ask, it's a legacy implementation, unfortunately)

The initial deployment seems to go fine using the 'upload' strategy however due to limitations with rsync and our setup limiting write speeds, when it gets to the deploy:vendor task it is timing out and simply taking forever (if i pass in the default timeout option as null).

Is there ultimately any other approach to the deployment we could take whilst still using laravel-deployer?

Tia

**Comment by lorisleiva** [comment]
Hi there 👋 

That's a tricky one. Have you tried just doing a `basic` strategy so that everything is "re-built" on the server instead of being uploaded via `rsync`.

I know it might seem like a waste since its already built on GitLab's pipelines but, in your case, that might actually be faster.

Let me know how you get on. 🍀

**Comment by CNSam** [comment]
Hey @lorisleiva,

Thanks for the response. It was actually down to the setup of FreeNas and the mount point settings. All is fine now, thank you
