### ISSUE TITLE
deploy:shared can not update shared files,right?

### ISSUE THREAD

**Issue by callect** [lorisleiva/laravel-deployer#107]
I use gitlab CI to deploy laravel programs.
Usually I use php artisan deploy my.domain -s upload to deploy new version.
But I found the .env file will not be updated unless it deleted by ssh before deploy.
my deploy.php:
```
'strategies' => [
    //
    'upload' => [
      'hook:start',
      'deploy:prepare',
      'deploy:lock',
      'deploy:release',
      'deploy:update_code',
      'upload',
      'deploy:shared',
      'deploy:writable',
      'hook:ready',
      'deploy:symlink',
      'deploy:unlock',
      'cleanup',
      'hook:done',
    ],
  ]...
```

**Comment by lorisleiva** [comment]
Hi there 👋 

Yes, this is by design. Any shared files or folders are relative to your host and therefore will not be updated between releases unless they are missing.

If you'd like to edit your shared files, I suggest setting up the `shared_files` option ([see documentation](https://github.com/lorisleiva/laravel-deployer/blob/8d014534ea9b9b639fde34e21e8cc86c0b76c34e/docs/all-options.md)).

<img width="1014" alt="Screenshot 2019-05-13 at 07 46 36" src="https://user-images.githubusercontent.com/3642397/57601073-765c3300-7553-11e9-846c-2a2957062c35.png">

**Comment by callect** [comment]
hi lorisleiva,
u mean if  i set shared_files example shared_files: ['.env'], the ENV file will be updated per released?

**Comment by lorisleiva** [comment]
No, you need to remove it from this array if you want the `.env` file *not* to be shared, therefore allowing it to update at every release.

**Comment by callect** [comment]
OK, I get you mean yet. Thank you.
