### ISSUE TITLE
upload_options ignored

### ISSUE THREAD

**Issue by Jamesking56** [lorisleiva/laravel-deployer#118]
In the `upload` strategy, I'm trying to exclude some files and folders for upload.

Following the documentation, I set `upload_options` but its getting completely ignored. Its even uploading the `.git` directory!

Laravel 5.8.19
Laravel Deployer v0.2.11

**Comment by lorisleiva** [comment]
Hi there 👋 

Can you please provide me with the content of your `upload_options`?

**Comment by Jamesking56** [comment]
```
    'upload_options' => [
            'options' => [
                '--exclude=.git',
                '--exclude=.idea',
                '--exclude=/vendor',
                '--exclude=node_modules',
                '--exclude=/config/deployer.php',
                '--exclude=/.gitlab-ci.yml',
                '--exclude=/.editorconfig',
                '--exclude=/.gitattributes',
                '--exclude=/.gitignore',
                '--exclude=/.php_cs',
                '--exclude=/docker',
                '--exclude=/docker-compose.yml',
                '--exclude=/phpstan.neon.dist',
                '--exclude=/phpunit.xml',
                '--exclude=/server.php',
                '--exclude=/vessel',
                '--exclude=/webpack.mix.js',
            ]
        ]
```

**Comment by lorisleiva** [comment]
Okay, so that should work fine.

The reason you can still see some of those folders/files in your host is because the `upload` strategy still performs the task `deploy:update_code` (which basically git clones your repository) before performing the upload.

This is done by design in order to improve the performances of your upload since only the difference between your host and your local machine will be uploaded via `rsync`.

Does that make sense?

**Comment by Jamesking56** [comment]
Yeah it does, but I don't really want these files on my production server. I can understand they need to be copied locally into `vendor` but why are they also in production?

**Comment by lorisleiva** [comment]
They do not need to be in production but it's a side effect of using `git clone` prior to uploading in order to increase the performance of your deployment. Everything is a tradeoff and the official strategies are mostly here to provide a starting point to its users. That's why the package allows you to create your own strategies and tasks.

In your case, you could either create a task that removes those extra files/folders or you could tweak the `upload` strategy to exclude the `deploy:update_code` task.

**Comment by Jamesking56** [comment]
Would using the `local` strategy do the same thing?

**Comment by lorisleiva** [comment]
Yeah the local strategy is basically the same as the basic strategy except that it build your asset (typically npm install and npm run prod) on your local machine before sending the compiled files to your host. So you’d still have those file/folders on your host if they are present in your repository.

But honestly creating your own strategy is pretty simple. If you just re-write the upload strategy without the `update_code` task then you should have the desired behaviour.

**Comment by Jamesking56** [comment]
Yep can confirm it worked :+1:
