### ISSUE TITLE
Different command based on stage

### ISSUE THREAD

**Issue by Jamesking56** [lorisleiva/laravel-deployer#120]
Hello,

If I have two stages, `staging` and `production`, how can I get Laravel to reset the DB and run seeders in staging, but just to do a standard `migrate` in production?

**Comment by lorisleiva** [comment]
Hi there 👋 

Unfortunately, at the moment there is no way to define "hooks" that are host-specific. You could either:
- Create a different strategy that includes the task `artisan:db:seed` and use that in your `staging` host.
- Create a new custom task that only runs `php artisan db:seed` when `{{stage}}` is `staging`.

In a future version, I'd really like to add more flexibility with hooks altogether. This would include creating your own custom hooks and having the possibility to make them host-specific.

I hope this helps.

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm closing this issue since Laravel Deployer is no longer the package it used to be and I recommend using Deployer directly for your Laravel applications from now on.

I've written a series of detailed tutorials to get started with Deployer called "[Deploy your Laravel app from scratch](https://lorisleiva.com/deploy-your-laravel-app-from-scratch)".

Thank you for all the support I've had whilst maintaining this package. I'm now also a maintainer of the Deployer library so feel free to open Laravel-related discussions on the repo and I'll help you there.

Happy deploying! 🌺

**Comment by haideritx** [comment]
Any update on this, how would we achieve this. 
I followed the tutorial, but I am not sure, how to implement it through that.
