### ISSUE TITLE
Deployer doesn't compile assets

### ISSUE THREAD

**Issue by forPelevin** [lorisleiva/laravel-deployer#15]
Hi! I added assets compiling configuration in deploy.php config. Now it looks like:
```
        'build'   => [
            'npm:install',
            'npm:production',
        ],
```
but when I called `php artisan deploy` it just copy my repo directory without compiling assets. What I do wrong?

**Comment by lorisleiva** [comment]
Hi there, what deployment strategy are you using? Could you also provide me with the output of `php artisan deploy -vvv` ?

**Comment by lorisleiva** [comment]
Odd, it does not even try to execute the npm tasks. Could you please show me the output of `php artisan deploy:dump strategy:basic` ?

**Comment by forPelevin** [comment]
```
php artisan deploy:dump strategy:basic
The task-tree for strategy:basic:
└── strategy:basic
    ├── hook:start
    ├── deploy:prepare
    ├── deploy:lock
    ├── deploy:release
    ├── deploy:update_code
    ├── deploy:shared
    ├── deploy:vendors
    ├── hook:build
    ├── npm:install [after:hook:build]
    ├── npm:production [after:hook:build]
    ├── deploy:writable
    ├── hook:ready
    ├── deploy:symlink
    ├── deploy:unlock
    ├── cleanup
    └── hook:done
```

**Comment by lorisleiva** [comment]
This is very weird. The npm tasks are clearly registered but not ran. A few questions:
* Did you commit and push your configuration changes?
* Could you please run `php artisan deploy:run strategy:basic` and show me the output?

**Comment by forPelevin** [comment]
Hi! I'm sorry for the long answer.
1. Yeah. I did it.
2. Thanks, it is solves my issue. I thought that basic strategy is used by default so I don't need to specify it explicitly.

**Comment by lorisleiva** [comment]
Hi, no it is a bug because it should be done by default when running `php artisan deploy`. I just wanted to know how deep the bug was.

Could you please tell me which version of the package you are using? I’ll do some digging on my side to see what could cause that problem. I don’t want you to type that horrendous command every time you need to deploy ^^

**Comment by forPelevin** [comment]
Hi! I appreciate your concern)
I use 0.2.0 version.

**Comment by lorisleiva** [comment]
It looks like its an [issue with deployer](https://github.com/deployphp/deployer/issues/1427) before version `6.1`. The [PR that fixes that](https://github.com/deployphp/deployer/pull/1364) have been tagged in version `6.0.4`.

Laravel Deployer requires deployer's version `^6.1` so it normally shouldn't affect us.

The only thing I can think of for now is that there are some issues with your composer dependencies. 
- Could you maybe check in your `composer.lock` which version of `deployer/deployer` you end up using?
- You could also try to upgrade Laravel Deployer to version `0.2.2` to see if it makes `deployer/deployer` upgrade to the right version.

**Comment by forPelevin** [comment]
My `deployer/deployer` version is `6.2.0`

**Comment by lorisleiva** [comment]
I've just upgraded to `6.2.0` locally as well and a lot of tests are failing. I'm going to look into that today. Maybe deployer's latest release isn't stable. In the mean time you can downgrade to deployer `6.1` and things should work as expected.

Thank you for reporting this.

**Comment by forPelevin** [comment]
Yeah, downgrading of deployer to `6.1` solves the issue. I run `php artisan deploy` and everything works fine. Thanks!

**Comment by lorisleiva** [comment]
Glad it helped. 🙂 

It's very odd because:
- The commits from `6.1` to `6.2` don't affect the `invoke` method which is responsible for calling tasks within another task. 
- All tests are passing using deployer `6.2`
- I upgraded deployer to `6.2` on one of my projects and deployment worked as expected

Thus, I am going to close that issue until someone else experiences the same problem. Thank you for your help during this process.
