### ISSUE TITLE
Cannot install 0.2.16...

### ISSUE THREAD

**Issue by telkins** [lorisleiva/laravel-deployer#154]
When I try to install this package, I get the following error:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove symfony/routing v4.4.1
    - Conclusion: don't install symfony/routing v4.4.1
...
```

I suspect it's related to a newer version of Laravel Framework:
```
$ composer depends symfony/routing
laravel/framework  v6.6.1  requires  symfony/routing (^4.3.4)
```

I'm happy to provide any more information, if needed.  Thanks in advance for any help.

**Comment by lorisleiva** [comment]
Hi there 👋 

Thank you for raising this issue. It should just be a dependency that needs updating.

I'll have a look at it as soon as I've got a minute.

**Comment by lorisleiva** [comment]
I've updated the composer dependencies. I have a feeling that the issue came from the `composer.json` not specifying `"prefer-stable": true` since it was basically locking commit-shas instead of proper stable versions.

I've pushed the changes and tagged a new version [`v0.2.17`](https://github.com/lorisleiva/laravel-deployer/releases/tag/v0.2.17).

@telkins Could you please let me know if this fixes your issue?

**Comment by telkins** [comment]
I'll try to take a look over the next day or so....and then post my findings here.

**Comment by telkins** [comment]
Well, I decided to just try it really quick...and it was successful.  Thx.

Now, I have to get it up/running like my current envoyer-based deployment script...!  ;-)
