### ISSUE TITLE
Is it possible to rollback also changes made in DB (migrations)?

### ISSUE THREAD

**Issue by ckissi** [lorisleiva/laravel-deployer#158]
I wonder if it's possible to make also migration rollbacks when I rollback to the previous version with the deployer.  I usually add some new fields to DB tables.

**Comment by lorisleiva** [comment]
Hi there 👋

That would be a cool feature. When rolling back we could check the difference between migration files (let's name that `X`) and if the earlier release has strictly fewer migrations than the current release than we could ask the user if they'd like us to run `php artisan migrate:rollback --step=X`.

However, currently, when rolling back we mostly delegate the task to DeployerPHP so this would very likely be a big task.

Another issue I see with the "Would you like us to run `...` for you? [y/N]" approach is that if developers are using `php artisan deployer:rollback` in a CI environment or any other environment that does not handle user interactions, this will basically stop the process since we'll be waiting for a response that we won't get.

That's my two cents on the matter. I'll leave that open to see if other users would find that interesting and if they have better suggestions on how to implement this.

**Comment by pedzed** [comment]
What should the behavior be if there's data?

- In case of a newly created a column
- In case of an updated a column (name or type)
- In case of a deleted column

This is quite a big feature. I can't quickly think about other relevant scenarios though.

**Comment by lorisleiva** [comment]
Well, rolling back a migration will simply call the `down` method of your Laravel migration file. It will be up to the developer to define their custom logic for migrating back and forward not only the schema but also the content of their database.

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm closing this issue since Laravel Deployer is no longer the package it used to be and I recommend using Deployer directly for your Laravel applications from now on.

I've written a series of detailed tutorials to get started with Deployer called "[Deploy your Laravel app from scratch](https://lorisleiva.com/deploy-your-laravel-app-from-scratch)".

Thank you for all the support I've had whilst maintaining this package. I'm now also a maintainer of the Deployer library so feel free to open Laravel-related discussions on the repo and I'll help you there.

Happy deploying! 🌺
