### ISSUE TITLE
'deploy:update_code' in local strategy

### ISSUE THREAD

**Issue by dostrog** [lorisleiva/laravel-deployer#167]
In local strategy there is 'deploy:update_code' task with 'git clone' on release folder and then there is 'local:upload' with rsync inside to the same folder. 

I would like just rsync builded tree without git clone by 'deploy:update_code'. Is 'deploy:update_code' in local strategy included by mistake? If it's not, how can I disable this task in local strategy (any options)?

**Comment by lorisleiva** [comment]
Hi there 👋 

The `deploy:update_code` was added for performance purposes. Since the git clone uses the previous deployment as a cache this will very quickly build up your repository to the previous deployment state to which we add a `rsync` which is going to add/edit/delete any files that have changed since the last deployment instead of uploading the entire repository at every deployment.

That being said, if you still want to remove the `deploy:update_code` from the local strategy you'd simply need to create a new strategy and copy/paste all the tasks of the local strategy except this one.

Something like that:

```php
// config/deploy.php

'strategies' => [
    'my_local_strategy' => [
        'hook:start',
        'local:build',
        'deploy:prepare',
        'deploy:lock',
        'deploy:release',
        // 'deploy:update_code', <- Removed
        'local:upload',
        'deploy:shared',
        'deploy:vendors',
        'deploy:writable',
        'hook:ready',
        'deploy:symlink',
        'deploy:unlock',
        'cleanup',
        'local:cleanup',
        'hook:done',
    ],
],
```

See https://github.com/lorisleiva/laravel-deployer/blob/master/docs/overview-strategy-create.md
