### ISSUE TITLE
Show deployer release number in frontend

### ISSUE THREAD

**Issue by taalas** [lorisleiva/laravel-deployer#175]
Hi!

Is there any way to show the current deployer release number in the frontend (or a best practice approach on how to achieve this)?

Thanks!

**Comment by lorisleiva** [comment]
Hi there 👋 

That's a good question. Technically, by default, the version number is the basename of the directory that is currently being used in production. However, you wouldn't have such information in your local machine for example, which makes it difficult to expose this version in a reliable fashion. Alternatively, there is a file keeping track of releases versions and their dates within the `.dep` folder but the same issue mentioned above apply here.

It's definitely an interesting feature and a good exercise on creating a Deployer task that will expose that information in a more useful and standardised way.

**Comment by asafov** [comment]
For frontend not a bad idea to use laravel-mix with versioning.
Another way to get current release for deployed project is:
`$release = basename (base_path());`

**Comment by asafov** [comment]
@lorisleiva BTW, i spoke with Anton, and he said that if he will have some free time, he will do more constructed output of CLI (JSON for example). At this moment we only can reload Table class for example, for repack it.

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm closing this issue since Laravel Deployer is no longer the package it used to be and I recommend using Deployer directly for your Laravel applications from now on.

I've written a series of detailed tutorials to get started with Deployer called "[Deploy your Laravel app from scratch](https://lorisleiva.com/deploy-your-laravel-app-from-scratch)".

Thank you for all the support I've had whilst maintaining this package. I'm now also a maintainer of the Deployer library so feel free to open Laravel-related discussions on the repo and I'll help you there.

Happy deploying! 🌺
