### ISSUE TITLE
Package deployer/recipes is abandonned

### ISSUE THREAD

**Issue by nonovd** [lorisleiva/laravel-deployer#188]
Recipes moved to https://github.com/deployphp/deployer/tree/master/contrib

**Comment by lorisleiva** [comment]
Hi there 👋 

Thank you for raising this issue.

I'll leave that open until I have some time to migrate these recipes files or until someone creates a PR.

🙇

**Comment by tariq86** [comment]
It looks like the latest release of [deployphp/deployer](https://github.com/deployphp/deployer) ([v6.8.0](https://github.com/deployphp/deployer/tree/v6.8.0)) doesn't have the new `contrib/` directory that they're telling you to use now. I see the changes in `master`, so we probably have to wait until the next major release before removing this dependency.

**Comment by lorisleiva** [comment]
Thanks for the heads up. Let's wait until this is ready before making the switch. 👌

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm closing this issue since Laravel Deployer is no longer the package it used to be and I recommend using Deployer directly for your Laravel applications from now on.

I've written a series of detailed tutorials to get started with Deployer called "[Deploy your Laravel app from scratch](https://lorisleiva.com/deploy-your-laravel-app-from-scratch)".

Thank you for all the support I've had whilst maintaining this package. I'm now also a maintainer of the Deployer library so feel free to open Laravel-related discussions on the repo and I'll help you there.

Happy deploying! 🌺
