### ISSUE TITLE
Task firstdeploy:cleanup doesn't work on Windows

### ISSUE THREAD

**Issue by IP-Developer** [lorisleiva/laravel-deployer#191]
As you can see in the image, `firstdeploy:cleanup` doesn't wait for user input and doesn't delete the files. I'm using the latest version of OpenSSH for Windows.

![image](https://user-images.githubusercontent.com/2005081/86046578-1a55b600-ba56-11ea-9b3b-9a34c1b074b8.png)

**Comment by lorisleiva** [comment]
Hi there 👋 

I've noticed this on a pair-programming session I did with a Windows user.

To be honest, I've got no idea why the shell does not allow a TTY on windows. We ended up running this manually on the server by copy/pasting the list of deleted files above. 🙈

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm closing this issue since Laravel Deployer is no longer the package it used to be and I recommend using Deployer directly for your Laravel applications from now on.

I've written a series of detailed tutorials to get started with Deployer called "[Deploy your Laravel app from scratch](https://lorisleiva.com/deploy-your-laravel-app-from-scratch)".

Thank you for all the support I've had whilst maintaining this package. I'm now also a maintainer of the Deployer library so feel free to open Laravel-related discussions on the repo and I'll help you there.

Happy deploying! 🌺
