### ISSUE TITLE
Upload strategy does git clone on server

### ISSUE THREAD

**Issue by jeversen** [lorisleiva/laravel-deployer#202]
Hi, it seems that the 'upload'-strategy contains a task 'update_code' which is executing a git-clone on the destination-host. Isn't this a bug? To me it seems that the 'upload' task should move the code to de destination-host.

In my case I'm building and testing my application in a Gitlab-pipeline. And in the end i'm using laravel-deployer to upload the built application to my production server. No need to do git-clone's on the production-server.

Is this a bug? Or is this intended behaviour and I'm doing it wrong? :)

thanks for the great work!

**Comment by lorisleiva** [comment]
Hi there 👋 

I know it can be a bit confusing but it's actually a feature, not a bug. 😅 

This is for performance improvements since the `update_code` task will use the previous release as a cache so that the uploading will only affect changes between your repository code and what you actually want to upload.

I've written [a more detail answer](https://github.com/lorisleiva/laravel-deployer/issues/167#issuecomment-605434697) to someone asking a similar question for the `local` strategy if that helps. 🙂

**Comment by jeversen** [comment]
Hi Loris,

thanks for taking the time to formulate an answer; it makes total sense when you explain it this way!

keep up the good work!
