### ISSUE TITLE
Failure in artisan:horizon:terminate task is silent

### ISSUE THREAD

**Issue by eronisko** [lorisleiva/laravel-deployer#210]
In our set-up, we have the Horzion process running as a different user (`www-data`) than the deployer user (`lab`). 

When tun the `artisan:horizon:terminate` hook, the deployment seems to get through fine, but in fact, it fails to terminate Horizon. This is what shows up when run with `-vvv`:

```
➤ Executing task artisan:horizon:terminate
[webumenia.sk] > php7.4 /var/www/register-architektury.sk/releases/157/artisan horizon:terminate
[webumenia.sk] < Sending TERM Signal To Process: 18629
[webumenia.sk] < Failed to kill process: 18629 (Operation not permitted)
```

We solved problem this with our own hook (using `sudo` on that command), but it would've been good to know something had failed without having to debug.

I don't have a solution for this, but I'd be happy to help out with a PR if you can think of one.

**Comment by lorisleiva** [comment]
Hi there 👋 

Thanks for reporting this. I've got no idea how to get around this I'm afraid.

I'll leave this open and perhaps another user can suggest a solution.

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm closing this issue since Laravel Deployer is no longer the package it used to be and I recommend using Deployer directly for your Laravel applications from now on.

I've written a series of detailed tutorials to get started with Deployer called "[Deploy your Laravel app from scratch](https://lorisleiva.com/deploy-your-laravel-app-from-scratch)".

Thank you for all the support I've had whilst maintaining this package. I'm now also a maintainer of the Deployer library so feel free to open Laravel-related discussions on the repo and I'll help you there.

Happy deploying! 🌺
