### ISSUE TITLE
git not found when i run laravel command：php artisan horizon

### ISSUE THREAD

**Issue by mouyong** [lorisleiva/laravel-deployer#218]
![image](https://user-images.githubusercontent.com/10336437/99882003-3bfb4800-2c58-11eb-8a44-9e302094ccad.png)

![image](https://user-images.githubusercontent.com/10336437/99882012-4ae1fa80-2c58-11eb-8aa2-d0d1790a1816.png)

![image](https://user-images.githubusercontent.com/10336437/99882030-7533b800-2c58-11eb-9b5f-396b57694589.png)

**Comment by mouyong** [comment]
this project deploy inside in docker container. it doesn't need git.

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm closing this issue since Laravel Deployer is no longer the package it used to be and I recommend using Deployer directly for your Laravel applications from now on.

I've written a series of detailed tutorials to get started with Deployer called "[Deploy your Laravel app from scratch](https://lorisleiva.com/deploy-your-laravel-app-from-scratch)".

Thank you for all the support I've had whilst maintaining this package. I'm now also a maintainer of the Deployer library so feel free to open Laravel-related discussions on the repo and I'll help you there.

Happy deploying! 🌺
