### ISSUE TITLE
Yarn Task Fails on Deploy

### ISSUE THREAD

**Issue by stevepop** [lorisleiva/laravel-deployer#229]
I added the following to my build array
```
 'build' => [
        'yarn:install',
        'yarn:production'
],
```

When I deploy, it fails with the following error;
```
The command "which yarn" failed.

  Exit Code: 1 (General error)
```

I can confirm that I have yarn installed via NVM on the server;
```
intrinsic@stage:~$ which yarn
/home/intrinsic/.nvm/versions/node/v15.7.0/bin/yarn
```

I am able to run the same command locally, so I really don't know what is happening here.

**Comment by stevepop** [comment]
I was able to resolve the above by creating a symlink to `/usr/yarn` but now I am getting the following error;
```
In Client.php line 103:

  The command "cd /www/caregroup.com/releases/79 && (/bin/yar
  n production)" failed.

  Exit Code: 2 (Misuse of shell builtins)

  Host Name: caregroup.com

  ================
  error Command failed with exit code 2.


deploy [-p|--parallel] [-l|--limit LIMIT] [--no-hooks] [--log LOG] [--roles ROLES] [--hosts HOSTS] [-o|--option OPTION] [--] [<stage>]


   Symfony\Component\Process\Exception\ProcessFailedException

  The command "vendor/bin/dep --file=vendor/lorisleiva/laravel-deployer/.build/deploy.php deploy --ansi" failed.

Exit Code: 2(Misuse of shell builtins)
```

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm closing this issue since Laravel Deployer is no longer the package it used to be and I recommend using Deployer directly for your Laravel applications from now on.

I've written a series of detailed tutorials to get started with Deployer called "[Deploy your Laravel app from scratch](https://lorisleiva.com/deploy-your-laravel-app-from-scratch)".

Thank you for all the support I've had whilst maintaining this package. I'm now also a maintainer of the Deployer library so feel free to open Laravel-related discussions on the repo and I'll help you there.

Happy deploying! 🌺
