### ISSUE TITLE
Trouble with multiple PHP-Versions on deployment

### ISSUE THREAD

**Issue by Vmadmax** [lorisleiva/laravel-deployer#231]
Hi,
I have some trouble with different PHP-Versions.

My default php version is 7.3. Now I would like to deploy with my php7.4 binary 
 `php7.4 artisan deploy testing` is not working, because of this error:

```
+ php7.4 artisan deploy testing

PHP Parse error:  syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /var/lib/jenkins/workspace/xxx/app/Helpers/MailjetHelper.php on line 23



   Symfony\Component\Process\Exception\ProcessFailedException 



  The command "vendor/bin/dep --file=vendor/lorisleiva/laravel-deployer/.build/deploy.php deploy testing --ansi" failed.
```
  
I need to set the php binary for the command `"vendor/bin/dep ..."`.
Is there any option to do that? I don't find anything.

Thanks

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm closing this issue since Laravel Deployer is no longer the package it used to be and I recommend using Deployer directly for your Laravel applications from now on.

I've written a series of detailed tutorials to get started with Deployer called "[Deploy your Laravel app from scratch](https://lorisleiva.com/deploy-your-laravel-app-from-scratch)".

Thank you for all the support I've had whilst maintaining this package. I'm now also a maintainer of the Deployer library so feel free to open Laravel-related discussions on the repo and I'll help you there.

Happy deploying! 🌺
