### ISSUE TITLE
How to pass custom option to task?

### ISSUE THREAD

**Issue by lucianomelotti** [lorisleiva/laravel-deployer#232]
I need to pass parameters to my custom task on run.
I should do something similar: 
`php artisan deploy:run mytask param1=value1 param2=value2`

How can I do it?

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm closing this issue since Laravel Deployer is no longer the package it used to be and I recommend using Deployer directly for your Laravel applications from now on.

I've written a series of detailed tutorials to get started with Deployer called "[Deploy your Laravel app from scratch](https://lorisleiva.com/deploy-your-laravel-app-from-scratch)".

Thank you for all the support I've had whilst maintaining this package. I'm now also a maintainer of the Deployer library so feel free to open Laravel-related discussions on the repo and I'll help you there.

Happy deploying! 🌺

---

P.S.: With Deployer you can do `dep my:task -o param1=value1 -o param2=value2`.
