### ISSUE TITLE
Backup DB before deploy

### ISSUE THREAD

**Issue by jrrmcalcio** [lorisleiva/laravel-deployer#234]
Hello i'm new to this tool, so sorry if this was answered before.  How can I ensure a backup of my database is made before deployment?

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm closing this issue since Laravel Deployer is no longer the package it used to be and I recommend using Deployer directly for your Laravel applications from now on.

I've written a series of detailed tutorials to get started with Deployer called "[Deploy your Laravel app from scratch](https://lorisleiva.com/deploy-your-laravel-app-from-scratch)".

Thank you for all the support I've had whilst maintaining this package. I'm now also a maintainer of the Deployer library so feel free to open Laravel-related discussions on the repo and I'll help you there.

Happy deploying! 🌺
