### ISSUE TITLE
Compile assets "npm run production" not running

### ISSUE THREAD

**Issue by sluxzer** [lorisleiva/laravel-deployer#235]
Hey there

i'm trying to figure out how to compile assets on this wrapper.

I'm reading this docs: [How to compile assets on deploy using npm (or yarn)?
](https://github.com/lorisleiva/laravel-deployer/blob/main/docs/how-to-npm.md)

but i don't understand how to hook the relevant tasks in deployment flow.

my deploy.php:
```
    'hooks' => [
        // Right before we start deploying.
        'start' => [
            //
        ],

        // Code and composer vendors are ready but nothing is built.
        'build' => [
            'npm:install',
            'npm:production',
        ],

        // Deployment is done but not live yet (before symlink)
        'ready' => [
            'artisan:storage:link',
            'artisan:view:clear',
            'artisan:config:cache',
            'npm:production',
            'artisan:optimize'
        ],

        // Deployment is done and live
        'done' => [
            //
        ],

        // Deployment succeeded.
        'success' => [
            //
        ],

        // Deployment failed.
        'fail' => [
            //
        ],

        // After a deployment has been rolled back.
        'rollback' => [
            //
        ],
    ],
```

i'm using "basic" strategy, and using github actions, but on hooks ready, i'm not seeing any npm is running

i now this is some how rookie mistake.

Thank you

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm closing this issue since Laravel Deployer is no longer the package it used to be and I recommend using Deployer directly for your Laravel applications from now on.

I've written a series of detailed tutorials to get started with Deployer called "[Deploy your Laravel app from scratch](https://lorisleiva.com/deploy-your-laravel-app-from-scratch)".

Thank you for all the support I've had whilst maintaining this package. I'm now also a maintainer of the Deployer library so feel free to open Laravel-related discussions on the repo and I'll help you there.

Happy deploying! 🌺
