### ISSUE TITLE
Unable to deploy the source

### ISSUE THREAD

**Issue by yasithacp** [lorisleiva/laravel-deployer#237]
I was able to deploy the code using laravel deployer few months ago, but when I check today I am getting below error when I execute php artisan deploy. 

You need to set up the project dependencies using the following commands:
wget http://getcomposer.org/composer.phar
php composer.phar install

   Symfony\Component\Process\Exception\ProcessFailedException

  The command "vendor/bin/dep --file=vendor/lorisleiva/laravel-deployer/.build/deploy.php deploy --ansi" failed.

Exit Code: 1(General error)

Working directory: /Users/yasitha/projects/deployer

Output:
================

Error Output:
================

  at vendor/symfony/process/Process.php:267
    263▕      */
    264▕     public function mustRun(callable $callback = null, array $env = []): self
    265▕     {
    266▕         if (0 !== $this->run($callback, $env)) {
  ➜ 267▕             throw new ProcessFailedException($this);
    268▕         }
    269▕
    270▕         return $this;
    271▕     }

      +16 vendor frames
  17  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm closing this issue since Laravel Deployer is no longer the package it used to be and I recommend using Deployer directly for your Laravel applications from now on.

I've written a series of detailed tutorials to get started with Deployer called "[Deploy your Laravel app from scratch](https://lorisleiva.com/deploy-your-laravel-app-from-scratch)".

Thank you for all the support I've had whilst maintaining this package. I'm now also a maintainer of the Deployer library so feel free to open Laravel-related discussions on the repo and I'll help you there.

Happy deploying! 🌺
