### ISSUE TITLE
Users sometimes get errors during deployment

### ISSUE THREAD

**Issue by Jamesking56** [lorisleiva/laravel-deployer#240]
Sometimes during deployment, some users experience exceptions using the site as follows:

```
unlink(/home/sites/15a/5/564543e965/production/releases/88/storage/framework/cache/data/85/5f/855f92484c8c414d36c1b25cb24876e30229cbbf): No such file or directory
```

This is using the newer deployer and based off the example `deploy.php` script in this repo.

Any idea what could cause that?

**Comment by lorisleiva** [comment]
Hi, I don't know I'm afraid. I've never had that error. 🤔 

Are you using ACL for permissions?

**Comment by Jamesking56** [comment]
@lorisleiva Not using ACL no, I'm testing to see whether its to do with Opcache

**Comment by lorisleiva** [comment]
Oh that would make sense since it's trying to access a symlinked path. Do you have the following FastCGI parameters overridden in your Nginx config file?

```
fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
fastcgi_param DOCUMENT_ROOT $realpath_root;
```

They ensure the real path of the symlink is used instead.

**Comment by Jamesking56** [comment]
Unfortunately I don't have access to nginx settings, its shared hosting :(

**Comment by lorisleiva** [comment]
I'm afraid, if that's the error, there's not much you can do with a shared hosting. 😔

If the problem still persists on a server you can fully configure, feel free to open a discussion on Deployer directly. 🙂 

Now for the generic message haha:

---

I'm closing this issue since Laravel Deployer is no longer the package it used to be and I recommend using Deployer directly for your Laravel applications from now on.

I've written a series of detailed tutorials to get started with Deployer called "[Deploy your Laravel app from scratch](https://lorisleiva.com/deploy-your-laravel-app-from-scratch)".

Thank you for all the support I've had whilst maintaining this package. I'm now also a maintainer of the Deployer library so feel free to open Laravel-related discussions on the repo and I'll help you there.

Happy deploying! 🌺
