### ISSUE TITLE
php7.2-fpm reload fails permission denied

### ISSUE THREAD

**Issue by smalld64** [lorisleiva/laravel-deployer#26]
First of all thanks, great application... Getting an error when I attempt to use fpm reload. Permission denied no tty available. Script runs perfectly without the fpm reload option but I have to login and manually to reload php7.2-fpm service for the site to update. Platform Ubuntu 16.04 php7.2-fpm. I've tried setting /etc/sudoers NOPASSWD for the service with no luck. Any tips on how I can resolve this?

**Comment by lorisleiva** [comment]
Hi there 👋

I am having the exact same problem with some of my applications and it is driving me crazy. I've followed every instructions on Stack Overflow and it still won't work without a tty.

For those applications, I've had to downgrade to `7.1`. It is not a Laravel Deployer problem because I had the same issue when using the deployment script directly on Laravel Forge.

If you manage to find a solution to this issue, please don't hesitate to share it here. 🙏

**Comment by smalld64** [comment]
Hi There
Thanks for your reply. I thought I was alone. Anyway solved the problem on my machine. Ubuntu 16.04 using the following command.
$ sudo visudo
At the very end of the file entered the following line:
username ALL = NOPASSWD: /usr/sbin/service php7.2-fpm reload
substitute username for your deployer username save and exit file. In deploy config add php7.2-fpm run deploy and it worked.
could also test by the following
$ ssh username@host sudo /usr/sbin/service -S php7.2-fpm reload
errors and asks for tty without the above visudo line
works with the above visudo line.
Thanks again great App.

**Comment by lorisleiva** [comment]
Awesome! Thank you very much. Looking forward to try that with my applications 🙂

**Comment by lorisleiva** [comment]
@smalld64 Just to let you know that I've successfully make that work for my app but I had to add the line after the `sudo` group definition.

```bash
# ...

# User privilege specification
root	ALL=(ALL:ALL) ALL
# <-x- Adding it here does not work because the sudo group below also matches

# ...

# Allow members of group sudo to execute any command
%sudo	ALL=(ALL:ALL) ALL
forge	ALL=(ALL:ALL) NOPASSWD:/usr/sbin/service php7.2-fpm reload # <- Here it works
```

Hope that helps other people.
