### ISSUE TITLE
Unable to run db seed task

### ISSUE THREAD

**Issue by JeffBeltran** [lorisleiva/laravel-deployer#46]
First off this package is great, thank you! It works great for me with one minor issue...

When I try to deploy with the seed task, it will give me the error `Class 'Faker\Factory' not found` and if I jump on the server and run same command (`php artisan db:seed`) I'll get same error. However, if first run `composer install`, it will run the composer installs and then the seed command works. 

Here is the the task log 
```
✈︎ Deploying HEAD on dev.domain.com with upload strategy
➤ Executing task deploy:prepare
✔ Ok
➤ Executing task deploy:lock
✔ Ok
➤ Executing task deploy:release
✔ Ok
➤ Executing task deploy:update_code
✔ Ok
➤ Executing task upload
✔ Ok
➤ Executing task deploy:shared
✔ Ok
➤ Executing task deploy:vendors
✔ Ok
➤ Executing task deploy:writable
✔ Ok
➤ Executing task artisan:storage:link
✔ Ok
➤ Executing task artisan:view:clear
✔ Ok
➤ Executing task artisan:cache:clear
✔ Ok
➤ Executing task artisan:config:cache
✔ Ok
➤ Executing task artisan:migrate:fresh
✔ Ok
➤ Executing task artisan:db:seed
➤ Executing task deploy:failed
✔ Ok
➤ Executing task deploy:unlock
✔ Ok
```
it looks like the task to run the local composer install (deploy:vendors) is working... so I'm confused as to why I need to manually run composer install to get the packages installed...

For the sake of brevity I haven't copied over everything so if you need more information please just let me know. (I pretty much followed http://lorisleiva.com/laravel-deployment-using-gitlab-pipelines step for step if that helps)

Thanks in advance
Jeff

**Comment by lorisleiva** [comment]
Hi Jeff 👋 

I successfully reproduced your issue with one of my application and I now understand where the problem comes from.

The `fzaninotto/faker` package is by default set up as a dev dependencies in the `composer.json` of a Laravel application.

<img width="356" alt="screen shot 2018-09-05 at 10 45 22" src="https://user-images.githubusercontent.com/3642397/45082196-14f8e000-b0f9-11e8-90f2-537fe0ae4e32.png">

However, the command `deploy:vendors` of Laravel Deployer will only install production dependencies since at this point you should (in theory) not need any dev packages.

**You have two possible options.**

1. You simply move the `fzaninotto/faker` package from `require-dev` to `require`.
2. **(recommended)** You edit the composer options so that it also includes your dev dependencies. To do this, you'll simply need to set up the `composer_options` in your `config/deploy.php`, like this:

```php
'options' => [

    // This is the default value.
    'composer_options' => '{{composer_action}} --verbose --prefer-dist --no-progress --no-interaction --no-dev --optimize-autoloader'

    // This is probably what you want (no --no-dev flag).
    'composer_options' => '{{composer_action}} --verbose --prefer-dist --no-progress --no-interaction --optimize-autoloader'
]
```

Let me know how you get on. 🍀

**Comment by JeffBeltran** [comment]
Perfect! figured it had something to do with that but couldn't figure it out. Thanks a lot, and thanks for this amazing package.
