### ISSUE TITLE
CLI Options not supported

### ISSUE THREAD

**Issue by ohryan** [lorisleiva/laravel-deployer#48]
I want to be able to set a "default" branch for each stage with the option to override it via the command line.

Example hosts config:
```php
    'hosts' => [
        '8.8.8.4' => [
            'deploy_path' => '/var/www/vhosts/example.com',
            'stage'       => 'staging',
            'branch'      => 'develop',
        ],
        '8.8.8.8' => [
            'deploy_path' => '/var/www/vhosts/example.com',
            'stage'       => 'production',
            'branch'      => 'master',
        ]
    ],
```

I would expect that I could run something like this to deploy a hotfix branch for testing: `php artisan deploy --branch="hotfix/fix-branch" staging`. But this has no effect and instead uses `develop`.

**Comment by lorisleiva** [comment]
Hi there 👋 

It looks like this is an [issue from DeployerPHP](https://github.com/deployphp/deployer/issues/1424#issuecomment-346360399).

Apparently, at the moment, you can override global options from the CLI but not host options. 😕 

Since I proxy these CLI arguments to DeployerPHP I am coupled to their behaviour in DeployerPHP.

I hope this helps.
