### ISSUE TITLE
Why does the upload strategy require GIT on remote server?

### ISSUE THREAD

**Issue by michalwaskiw** [lorisleiva/laravel-deployer#61]
I'm not sure if I'm missing something there, but what's the point of must-having git on the server since we are trying to simply upload production ready code.

Isn't the update_code step unnecessary in that case?

**Comment by lorisleiva** [comment]
Hello, this has already been answered [in a previous issue](https://github.com/lorisleiva/laravel-deployer/issues/18#issuecomment-413541195). Copy/pasting here:

---
**Why is deploy:update_code needed in the upload strategy?** It's not. But because we upload our application via rsync, it will only upload the changes in our repository. If we do not run deploy:update_code we will start with an empty repository which will significantly increase the overload of our upload. Note that deploy:update_code is very cheap because it uses the previous releases as a cache.
