### ISSUE TITLE
deploy with windows

### ISSUE THREAD

**Issue by hexters** [lorisleiva/laravel-deployer#63]
how to deploy with windows ?

**Comment by lorisleiva** [comment]
Laravel Deployer is a wrapper around DeployerPHP which should work on Windows local machines. Since I haven't got any Windows computers myself, I suggest you try to find your issue [directly within the DeployerPHP repository](https://github.com/deployphp/deployer/issues?utf8=%E2%9C%93&q=windows).

Sorry I can't provide more help than this. 😕
