### ISSUE TITLE
.env file management

### ISSUE THREAD

**Issue by mehrdaad** [lorisleiva/laravel-deployer#7]
While deploying Laravel app, an empty ``.env`` is created on root of releases/1.  
I want to know if this file is copied from somewhere else or is just created while deploying.  
Second question, as normal, we don't share our ``.env`` on git.  
how to manage ``.env`` files while deploying? is there several strategies?  
I have used deployer before the method I use to use was copying ``.env.production`` from my machine to the server and rename it to ``.env`` but I think you will have a better solution.

**Comment by lorisleiva** [comment]
If a `.env` file already exists at the root of your `deploy_path` and this is your first deployment with Laravel Deployer, it will copy it from there. Otherwise it will create a new one.

If you'd like to update the `shared/.env` from a `.env.production` at every deployment you can create a task that does that and hook it into the deployment flow. Is that a strategy that you'd prefer?

**Comment by mehrdaad** [comment]
> If a .env file already exists at the root of your deploy_path and this is your first deployment with Laravel Deployer, it will copy it from there. Otherwise it will create a new one.  
I don't think is approach would be recommended for 2 reasons:  

- First  ``.env``  would never be present in ``deploy_path`` since the code is pulled and in general, ``.env`` files are ignored by ``.gitignore``.
- Second ``.env`` files used in local mode are for development purposed and wont' be the same config as in production.  
 

> If you'd like to update the shared/.env from a .env.production at every deployment you can create a task that does that and hook it into the deployment flow. Is that a strategy that you'd prefer?

Absolutely!  there is 2 common things among ``.env`` fils: 

- There are ignored in git.  
- All Laravel apps need a ``.env`` file to opertate correctly.  
So I think we should devise a strategy for deployments to handle ``.env`` file copying and managing natively.  
We can come up with several strategies for handling `` .env`` files. I'm open for chat for discussion about this.  
If there is a confusion, please ask.

**Comment by lorisleiva** [comment]
Maybe my previous message was a bit confusing. Let me try to explain that a bit better.

Indeed `.env` files and most storage sub folders are ignored by default on most Laravel projects. When you first deploy your application using Laravel Deployer, it will git clone your project on a new release folder. Thus, your development environment will never get deployed into production which is the expected behaviour. Instead, Laravel Deployer creates an empty `.env` file in the shared folder so that you have a unique source of truth to update your production environment. At this point, if you have a `.env.production` file on your project, you should manually copy/paste it into `shared/.env` on your first deployment.

If you are deploying a project using Laravel Deployer for the first time but the project is already live — i.e. a migration of deployment services — then it is likely that the root of your project **on your host** already has a working `.env` production file. If this is the case then Laravel Deployer will use that `.env` file instead of creating a new one on your first deployment. This has already been documented [here](https://github.com/lorisleiva/laravel-deployer/blob/master/docs/first-deploy.md).

Now, I understand that, in your case, you would rather update your `shared/.env` file at every deployment using the `.env.production` file present in your repository. This can easily be done by creating a new task and adding it after the hook `deploy:shared`. Creating a task is documented [here](https://github.com/lorisleiva/laravel-deployer/blob/master/docs/custom-tasks.md).

I hope this clears the confusions of your previous message.

**Comment by mehrdaad** [comment]
In fact I did write a long reply for this I don't know why it hasn't been published

**Comment by mehrdaad** [comment]
Any way I did listen to hook ``deploy:shared`` and uploaded my ``.env.production`` to server with ssh with command ``upload``.  
What's your favorite strategy in managin ``.env`` files in production.  
Do you copy them from another directory to server or just edit it on the server?
