### ISSUE TITLE
Problem with releases

### ISSUE THREAD

**Issue by daylaborers** [lorisleiva/laravel-deployer#72]
Hey there,

i have a Problem with a deploy on my live system. When i deploy on stage, everything is ok. When i deploy on live, sometimes i have the problems, that classes or routings doesn't work correctly. It looks like, that stuff from older releases are included. When i delete the older release folders, everything is fine. Anybody an idea?

Cheers
Ralf

**Comment by Nowi5** [comment]
Hi, what about sharing a log or some screenshots? Thanks ;-)

**Comment by daylaborers** [comment]
Hey, i have no logs or something. I see that an implemented Function doesn't work, or not work like it should. I delete the old releases, and everything is fine.

**Comment by lorisleiva** [comment]
👋 Hi there,

Unfortunately you are not providing enough information for us to help you debug this issue. Since the deployments are working on one host and not the other my guess would be that the OP cache of your production host does not work well with symlinks. If that's the case, I advise you to read this [troubleshooting section](https://github.com/lorisleiva/laravel-deployer/blob/7fd18a30d4d44c4567dc25d865508aa74c9a9318/docs/troubleshooting.md#my-changes-dont-show-up-after-a-deployment).

Otherwise, your guess is as good as mine.
