### ISSUE TITLE
Not a bug just a suggestion for tests

### ISSUE THREAD

**Issue by ludo237** [lorisleiva/laravel-deployer#81]
Hello.

First of all thanks for this great package ❤️ 

This is not a huge issue just a matter of form. When pulling this package in my project my IDE (PHPStorm) freaks out because it says that there're multiple definition of the `test` namespace because you have a generic namespace inside `fixtures/repository/tests` which does not follow your others tests namespace criteria like rest of the tests suite that use `namespace Lorisleiva\LaravelDeployer\Test;`

I think the solution is fairly easy and I would fix that if you don't have a plan for this.

Other than this, this package is extremely well made.

**Comment by lorisleiva** [comment]
Hi there 👋 

Thanks I’m really glad you like it! 🙃

Also thank you for spotting and reporting that. My tests are actually deploying locally each time a dummy Laravel app that lives in the `tests/fixtures` directory. This dummy app is causing a few problems with IDEs that I’m not sure how to avoid once and for all.

For example I use a plugin on VS Code that runs artisan commands and every single time it asks me which `artisan` script I’d like to use because it’s spotting both the main one and the one in my vendor folder provided by Laravel Deployer.

There might be something that can be done at the git or composer level to avoid including the tests in the first place.
