### ISSUE TITLE
Branch setting on hosts using the local strategy is ignored

### ISSUE THREAD

**Issue by Rainrider** [lorisleiva/laravel-deployer#90]
I'm using the local strategy to deploy to a host which has the branch setting set to `master`.

```
'hosts' => [
    'xx.xx.x.xx' => [
        'deploy_path' => '/var/www/html/xxx',
        'user' => env('DEPLOY_USER', 'user'),
        'http_user' => 'www-data',
        'strategy' => 'local',
        'branch' => 'master',
    ],
],
```

However it deploys the remote version of the current local branch.

Using `php artisan deploy --branch=master` seems to have effect and deploys the correct branch. The `deploy:info` task always displays the branch set in the config though (master in this case).

Also, the default value for branch is the current local branch, not master as stated in the current version of [all-options.md](https://github.com/lorisleiva/laravel-deployer/blob/4b40fcca5da17be65c017cc284cf279fb48b5255/docs/all-options.md).

**Comment by lorisleiva** [comment]
Hi there 👋 

Yes, you are correct, the `local` strategy is a bit different then the others because it bases itself from your **current directory** as a **cache** when you clone to a temporary directory. And of course your current directory might not be the branch you want to deploy.

To be honest, I use this strategy a lot but I never came across the scenario of not needed to deploy on master from master but I do acknowledge that **it is a bug and it must be fixed**.

I find it a bit weird though that adding the `--branch` option deploys on the correct branch since it's a simple option override from your config file.

I'd need to dedicate some time on this to find out how to fix this. In the meantime if anyone can point some directions that would be most appreciated.

Thank you for reporting this 👍

**Comment by Rainrider** [comment]
It seems the host config is not available to the local tasks in Deployer ([ref](https://github.com/deployphp/deployer/blob/ad8e77579d652df4d3042df1dcac19975e426442/src/Executor/SeriesExecutor.php#L57-L58))

> I find it a bit weird though that adding the `--branch` option deploys on the correct branch since it's a simple option override from your config file.

This works because of [this code](https://github.com/deployphp/deployer/blob/ad8e77579d652df4d3042df1dcac19975e426442/recipe/deploy/update_code.php#L24-L26).

Sadly I don't know how to proceed with this info. It probably makes more sense to do the deploy directly on the server in my case. Using the local strategy in its current state is prone to error and I don't want to push some other branch on production by accident :(

**Comment by lorisleiva** [comment]
I'm not sure because `input()->getOption('branch')` should be looking in both the configurations and the CLI options.

Anyway, I'll need to dig a bit more into this. In the meantime any help is appreciated. 🙂

**Comment by Rainrider** [comment]
> I'm not sure because `input()->getOption('branch')` should be looking in both the configurations and the CLI options.

It reads the "general" options, not the host specific ones. Also, the general options override the CLI options, which is odd to me, but maybe this is related to Deployer. To me it does not make sense to define the branch in general options. I want a specific branch to be deployed to a specific host and be able to override the branch for a certain host from the command line on occasion.

I also want to express my gratitude to you for putting Laravel Deployer together and sharing it with the community. Thank you very much!

**Comment by lorisleiva** [comment]
Hi, yeah this is definitely a behaviour orchestrated by DeployerPHP. Laravel Deployer is a wrapper around this very big ecosystem.

However, I _have_ been able to set up some host-specific `branch` options in the past without any problems. I just didn't try that with the `local` strategy yet.

So I think the issue here is that the `local` strategy uses tasks that are defined as `->local()` and these local tasks must resolve options in a different way then tasks that would be run directly on the host.

**Comment by lorisleiva** [comment]
@Rainrider Hi there 👋I know it has been almost a year now but have you managed to find a solution to this issue?

**Comment by Rainrider** [comment]
Hi @lorisleiva, sadly I haven't looked into it since then.

**Comment by lorisleiva** [comment]
@Rainrider No worries. In this case, allow me to close this issue since next time you look into it you'll likely have some new information and it'll make more sense to open a new issue. Let me know how you get on. 🙂
