### ISSUE TITLE
ErrorException after deploy

### ISSUE THREAD

**Issue by daylaborers** [lorisleiva/laravel-deployer#92]
Hey there,

we run a deployment to our staging system:
PHP 7.3.2 and Laravel 5.7.28

The deploy success, but we get two errors in Sentry:
1. Warning: unlink(/var/www/stage/releases/318/bootstrap/cache/routes.php): No such file or directory
2. User Deprecated: Passing a command as string when creating a "Symfony\Component\Process\Process" instance is deprecated since Symfony 4.2, pass it as an array of its arguments instead, or use the "Process::fromShellCommandline()" constructor if you need features provided by the shell.

Anybody knows what happens?

Thanks and cheers
Ralf

**Comment by lorisleiva** [comment]
Hi there 👋 

Thank you for reporting this, a couple a questions:
- Is that your first deployment or did it suddenly stopped working?
- What strategy are you using?

**Comment by daylaborers** [comment]
Hi,
we deploy since one year,

**Comment by lorisleiva** [comment]
Thanks for your quick reply.

Okay so I can discard the second error message. The first one is due to deleting a route cache file on the new release folder which seems strange to me since releases are usually created from scratch.

I'm assuming you're using the `artisan:route:cache` task which ensures any existing route caching is deleted before creating the new cache. Since the release is brand new it will not contain a previous cache file which creates that warning.

Here are related issues that I found online:
- https://laracasts.com/discuss/channels/laravel/error-clearing-cache-or-routes
- https://stackoverflow.com/questions/33713606/how-to-cache-configuration-in-laravel-inside-heroku-i-e-build-in-a-different-p

Does that answer you question?

**Comment by daylaborers** [comment]
I'm not sure, i do this:
```
'ready' => [
            'artisan:horizon:terminate',
            'artisan:storage:link',
            'artisan:view:clear',
            'artisan:cache:clear',
            'artisan:config:cache',
            'artisan:route:cache',
            'artisan:optimize',
            'artisan:migrate',
        ],
```

What i should do?

**Comment by lorisleiva** [comment]
It seems that you're doing the right thing. I'd remove the `artisan:optimize` task since that's now been removed from Laravel but that won't solve your problem here.

That warning is really harmless and makes sense but I'm not sure how to get rid of it. Have you tried to run `php artisan route:cache` directly from you server to see if you get the same warning?

**Comment by daylaborers** [comment]
Yes:
```
php artisan route:cache
Route cache cleared!
Routes cached successfully!
```

**Comment by lorisleiva** [comment]
Okay but can you confirm that you still received that warning in Sentry?

**Comment by daylaborers** [comment]
Yes

**Comment by lorisleiva** [comment]
Okay in this case I think it's an issue with your sensitivity level in Sentry. As I said before, this warning is perfectly legit but never shows anywhere outside of your Sentry panel.

Closing this as it is not something Laravel Deployer is in control of.
